### ISSUE TITLE
i'm dumb help

### ISSUE THREAD

**Issue by GodlySLPG** [mtadin/steelseries-wireless-battery-tray#15]
don't know what to do with "npm run make" command
![Screenshot 2022-09-18 022225](https://user-images.githubusercontent.com/63352632/190880521-bdd8092b-eb7b-40de-af10-c3d560150348.png)

**Comment by mtadin** [comment]
**NOTE**: I've added a [Release](https://github.com/mtadin/steelseries-wireless-battery-tray/releases) so you don't have to install it yourself, which I should have done a long time ago. You can download the prebuilt .zip from there.

Anyway, if you still want to build it manually:
As I can see from your screenshot, you seem to have run the script in the wrong place. Try downloading the code again, and then navigate inside of the "steelseries-wireles-battery-tray" folder with the [cd command](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd#examples).

The path should look something like this when you successfully navigate to the correct folder:
`D:\Projects\steelseries-wireless-battery-tray>`

Now you should be able to run `npm run make` if you have Node installed.

**Comment by GodlySLPG** [comment]
thanks for help
i used this release thing - much easier
it's the first project that i install from github and i don't know this stuff very well
anyway great project
i've been looking for something like this for a long time
steelseries should have feature like this in their app
maybe they are lacking some good devs like u
keep it up

**Comment by mtadin** [comment]
Thanks for the feedback! As for the edit, please open a new issue and I'll take a look sometime in the future.
