### ISSUE TITLE
Arctis 1 Wireless

### ISSUE THREAD

**Issue by hxnmi** [mtadin/steelseries-wireless-battery-tray#23]
the app crash after plugging arctis 1 wireless, any chance to make it support for my headset? thank you

**Comment by mtadin** [comment]
Hi, could you tell me if you tried a version from the [releases](https://github.com/mtadin/steelseries-wireless-battery-tray/releases) or did you compile it yourself?

**Comment by hxnmi** [comment]
i tried the [releases](https://github.com/mtadin/steelseries-wireless-battery-tray/releases ) one

**Comment by mtadin** [comment]
could you try the newer release labeled as [newerHeadsetsBeta](https://github.com/mtadin/steelseries-wireless-battery-tray/releases/tag/v2.0.1-newerHeadsetsBeta)?

**Comment by hxnmi** [comment]
i think it works, thank you!

![image](https://user-images.githubusercontent.com/85260485/224908512-9970312e-8244-4ca6-ae8a-8c8dacdf20df.png)
