### ISSUE TITLE
Tray Icon doesn't update

### ISSUE THREAD

**Issue by wamuumu** [mtadin/steelseries-wireless-battery-tray#25]
After launching the application, the tray icon image remains always fixed at 61% even if the true percentage is higher or lower.
![Immagine 2023-02-28 214546](https://user-images.githubusercontent.com/59065112/221975587-f7f9089c-a9c9-490e-8528-ad02b2158842.png)

**Comment by mtadin** [comment]
I've released version 2.0.1 that fixes this issue. Give it a try and report back if it works for you
